from myTools import *
# 获取窗口句柄
hwnd = 330016

wcl = WindowController(hwnd)

# sleep(1)

# 走到第一块地
print("开始")
wcl.key_press("r")
sleep(0.5)
wcl.key_down("a")
sleep(0.8)
wcl.key_down("w")
sleep(4)
wcl.key_up("a")
sleep(0.1)
wcl.key_up("w")
sleep(0.5)
wcl.mouse_move((600,300))
wcl.key_press("`")
wcl.mouse_move((630,300))
wcl.key_press("`")

# go_to_farm()
# sleep(0.5)
# pg.moveTo(screen_width, screen_height, duration=0)
# pg.dragRel(335, duration=duration, button="left")
# for i in range(4):
#     sleep(0.5)
#     pg.keyDown("w")
#     sleep(random_move())
#     pg.keyUp("w")
# sleep(0.5)
# pg.moveTo(screen_width, screen_height, duration=0)
# pg.dragRel(-222, duration=duration, button="left")
# sleep(0.5)
# pg.keyDown("w")
# sleep(random_move())
# pg.keyUp("w")
# sleep(0.5)
# pg.moveTo(screen_width, screen_height, duration=0)
# pg.dragRel(-222, duration=duration, button="left")
# for i in range(4):
#     sleep(0.5)
#     pg.keyDown("w")
#     sleep(random_move())
#     pg.keyUp("w")


# sleep(0.5)
# pg.moveTo(screen_width, screen_height, duration=0)
# pg.dragRel(222, duration=duration, button="left")
# sleep(0.5)
# pg.keyDown("w")
# sleep(random_move())
# pg.keyUp("w")
# sleep(0.5)
# pg.moveTo(screen_width, screen_height, duration=0)
# pg.dragRel(222, duration=duration, button="left")
# for i in range(4):
#     sleep(0.5)
#     pg.keyDown("w")
#     sleep(random_move())
#     pg.keyUp("w")


# sleep(0.5)
# pg.moveTo(screen_width, screen_height, duration=0)
# pg.dragRel(-223, duration=duration, button="left")
# sleep(0.5)
# pg.keyDown("w")
# sleep(random_move())
# pg.keyUp("w")
# sleep(0.5)
# pg.moveTo(screen_width, screen_height, duration=0)
# pg.dragRel(-222, duration=duration, button="left")
# for i in range(4):
#     sleep(0.5)
#     pg.keyDown("w")
#     sleep(random_move())
#     pg.keyUp("w")

# sleep(0.5)
# pg.moveTo(screen_width, screen_height, duration=0)
# pg.dragRel(223, duration=duration, button="left")
# sleep(0.5)
# pg.keyDown("w")
# sleep(random_move())
# pg.keyUp("w")
# sleep(0.5)
# pg.moveTo(screen_width, screen_height, duration=0)
# pg.dragRel(222, duration=duration, button="left")
# for i in range(4):
#     sleep(0.5)
#     pg.keyDown("w")
#     sleep(random_move())
#     pg.keyUp("w")

# sleep(0.5)
# pg.moveTo(screen_width, screen_height, duration=0)
# pg.dragRel(-223, duration=duration, button="left")
# sleep(0.5)
# pg.keyDown("w")
# sleep(random_move())
# pg.keyUp("w")
# sleep(0.5)
# pg.moveTo(screen_width, screen_height, duration=0)
# pg.dragRel(-222, duration=duration, button="left")
# for i in range(4):
#     sleep(0.5)
#     pg.keyDown("w")
#     sleep(random_move())
#     pg.keyUp("w")
